# Configuración del servidor
server.port=8081

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=@Postgre12

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.api-prefix=/api
app.cors.allowed-origins=http://localhost:5173

jwt.secret=K9fW3mQ8zR2pL5vN7xT1cY4aB6eG0dH9iS3kO5uM8aJ2eG4bT6fX1zR8vN0pQ7yZ
jwt.expiration=86400000